name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Setup Python and uv
      uses: ./.github/actions/setup-python-uv

    - name: Run tests
      run: |
        source .venv/bin/activate
        # see https://github.com/google-deepmind/mujoco/issues/1629
        # Use xvfb-run to provide virtual display for MuJoCo
        xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" pytest tests/ -v
