name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Python and uv
      uses: ./.github/actions/setup-python-uv
        
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest tests/ -v
